# Generated by Django 6.1.1 on 2026-09-18 05:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('room', 'Single Room'), ('flat', 'Flat/Apartment'), ('house', 'House'), ('hostel', 'Hostel'), ('pg', 'PG / Paying Guest'), ('studio', 'Studio Apartment')], default='room', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, help_text='Neighborhood / Area', max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit', max_digits=10)),
                ('price_negotiable', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('area_sqft', models.PositiveIntegerField(blank=True, help_text='Area in square feet', null=True)),
                ('floor', models.CharField(blank=True, help_text='e.g. 2nd Floor', max_length=20)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('furnishing', models.CharField(choices=[('furnished', 'Fully Furnished'), ('semi', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=20)),
                ('gender_preference', models.CharField(choices=[('any', 'Any'), ('male', 'Male Only'), ('female', 'Female Only'), ('family', 'Family Only')], default='any', max_length=10)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=True)),
                ('has_electricity', models.BooleanField(default=True)),
                ('has_security', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_lift', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
